version: '3.9'

services:
  grpc-user:
    build: ../grpc-jwt-login
    restart: always
    ports:
      - "50052:50052"
    depends_on:
      - grpc-admin
  grpc-admin:
    build: ../grpc-admin
    restart: always
    ports:
      - "50051:50051"
    depends_on:
      - db

  grpc-mail:
    build: ../grpc-mail
    restart: always
    ports:
      - 50053:50053
      - 3003:3003
    depends_on:
      - grpc-user
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=1234

  db:
    image: postgres:15.2-alpine3.17
    container_name: db
    environment:
      POSTGRES_PASSWORD: grpc-admin
      POSTGRES_USER: grpc-admin
      POSTGRES_DB: grpc-admin

    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grpc-admin"]
      interval: 3s
      timeout: 5s
      retries: 5